#!/usr/bin/env python3
"""Gera analise_comparativa.ipynb — carrega pcap_stats.json (pre-computado)."""
import json, os

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'analise_comparativa.ipynb')

def md(cid, src):
    return {"cell_type":"markdown","id":cid,"metadata":{},"source":src}

def code(cid, src):
    return {"cell_type":"code","execution_count":None,"id":cid,"metadata":{},"outputs":[],"source":src}

cells = []

# ── TITLE ────────────────────────────────────────────────────────────────────
cells.append(md("cell-title",
    "# Análise Comparativa — Todos os PCAPs\n\n"
    "Comparação direta entre tráfego benigno e 6 ataques SOME/IP.  \n"
    "Estatísticas pré-extraídas via `tshark` e salvas em `pcap_stats.json`."))

# ── CONFIG ───────────────────────────────────────────────────────────────────
cells.append(code("cell-config",
    "import subprocess, sys\n"
    "subprocess.check_call([sys.executable, '-m', 'pip', 'install', 'plotly', '-q'])\n"
    "\n"
    "import json, os\n"
    "import pandas as pd\n"
    "import numpy  as np\n"
    "import plotly.graph_objects as go\n"
    "from plotly.subplots import make_subplots\n"
    "from IPython.display import display, HTML\n"
    "import warnings; warnings.filterwarnings('ignore')\n"
    "\n"
    "STATS_FILE = os.path.join(os.path.dirname(os.path.abspath('__file__')),\n"
    "                           'pcap_stats.json')\n"
    "with open(STATS_FILE, encoding='utf-8') as f:\n"
    "    results = json.load(f)\n"
    "LABELS = list(results.keys())\n"
    "\n"
    "BG='#0f1117'; PANEL='#161b2e'; GRID='#2a3550'\n"
    "TEXT='#d0d8f0'; A='#4e7fff'; G='#7bff9c'\n"
    "T2='#7bffd9'; Y='#ffd97b'; P='#c07bff'\n"
    "O='#ff9d7b'; R='#ff7b7b'\n"
    "COLORS=[G,R,Y,A,T2,P,O]\n"
    "\n"
    "LB=dict(paper_bgcolor=BG,plot_bgcolor=PANEL,\n"
    "        font=dict(color=TEXT,family='monospace'),\n"
    "        title_font=dict(color=TEXT,size=15))\n"
    "\n"
    "_first=True\n"
    "def show(fig):\n"
    "    global _first\n"
    "    display(HTML(fig.to_html(full_html=False,\n"
    "                             include_plotlyjs='cdn' if _first else False)))\n"
    "    _first=False\n"
    "\n"
    "print(f'Carregados: {LABELS}')"))

# ── SECTION 1: OVERVIEW TABLE ────────────────────────────────────────────────
cells.append(md("cell-h1", "## 1. Visão Geral — Métricas por PCAP"))

cells.append(code("cell-overview",
    "rows=[(l,\n"
    "       f\"{r['n_frame']:,}\",\n"
    "       f\"{r['dur']:.0f}s\",\n"
    "       f\"{r['avg_pps']:,.0f}\",\n"
    "       f\"{r['peak_pps']:,}\",\n"
    "       f\"{r['n_si']:,}  ({r['n_si']/r['n_frame']*100:.1f}%)\",\n"
    "       f\"{r['n_sd']:,}\",\n"
    "       str(r['n_ips']),\n"
    "       str(r['ttl']),\n"
    "      ) for l,r in results.items()]\n"
    "\n"
    "headers=['PCAP','Frames','Duracao','Avg pkt/s','Peak pkt/s',\n"
    "         'SOME/IP','SOME/IP-SD','IPs unicos','TTLs']\n"
    "cols=list(zip(*rows))\n"
    "\n"
    "fig=go.Figure(go.Table(\n"
    "    header=dict(values=headers,fill_color=PANEL,\n"
    "                font=dict(color=A,size=12),align='left'),\n"
    "    cells=dict(values=[list(c) for c in cols],\n"
    "               fill_color=[[BG if i%2==0 else PANEL for i in range(len(rows))]\n"
    "                           for _ in headers],\n"
    "               font=dict(color=TEXT,size=11),align='left')))\n"
    "fig.update_layout(**LB,title='Visão geral por PCAP',height=320)\n"
    "show(fig)"))

# ── SECTION 2: PROTOCOL COMPOSITION ─────────────────────────────────────────
cells.append(md("cell-h2", "## 2. Composição do Tráfego por Protocolo"))

cells.append(code("cell-hier",
    "protos  =['SOME/IP (TCP)','TCP ctrl/ACK','SOME/IP-SD','SOME/IP (UDP)','IGMPv3','ARP']\n"
    "keys    =['n_si_tcp',    'n_tcp_c',     'n_sd',      'n_si_udp',    'n_igmp','n_arp']\n"
    "pcolors =[A,             R,             Y,            T2,            G,       P]\n"
    "\n"
    "fig=go.Figure()\n"
    "for proto,key,col in zip(protos,keys,pcolors):\n"
    "    vals=[results[l][key] for l in LABELS]\n"
    "    pcts=[v/results[l]['n_frame']*100 for l,v in zip(LABELS,vals)]\n"
    "    fig.add_trace(go.Bar(\n"
    "        name=proto, x=LABELS, y=pcts,\n"
    "        marker_color=col,\n"
    "        hovertemplate=f'{proto}: %{{y:.1f}}%<extra></extra>'))\n"
    "\n"
    "fig.update_layout(**LB,\n"
    "    title='Composicao por protocolo (% frames)',\n"
    "    barmode='stack', height=460,\n"
    "    xaxis=dict(title='PCAP',gridcolor=GRID),\n"
    "    yaxis=dict(title='% frames',gridcolor=GRID),\n"
    "    legend=dict(bgcolor=PANEL,bordercolor=GRID))\n"
    "show(fig)"))

# ── SECTION 3: MESSAGE TYPE ───────────────────────────────────────────────────
cells.append(md("cell-h3", "## 3. Distribuição de Message Type (SOME/IP)"))

cells.append(code("cell-msgtype",
    "mt_order=['NOTIFICATION','REQUEST','RESPONSE','REQUEST_NO_RETURN',\n"
    "          'ERROR','REQUEST_ACK','RQST_NRET_ACK','NOTIF_ACK']\n"
    "mt_col  =[R,A,G,Y,O,T2,P,A]\n"
    "\n"
    "fig=go.Figure()\n"
    "for mt,col in zip(mt_order,mt_col):\n"
    "    vals=[]\n"
    "    for l in LABELS:\n"
    "        n_si=results[l]['n_si']\n"
    "        cnt=results[l]['mt_counts'].get(mt,0)\n"
    "        vals.append(cnt/n_si*100 if n_si>0 else 0)\n"
    "    if any(v>0 for v in vals):\n"
    "        fig.add_trace(go.Bar(\n"
    "            name=mt, x=LABELS, y=vals,\n"
    "            marker_color=col,\n"
    "            hovertemplate=f'{mt}: %{{y:.1f}}%<extra></extra>'))\n"
    "\n"
    "fig.update_layout(**LB,\n"
    "    title='Message Type — % dos frames SOME/IP por PCAP',\n"
    "    barmode='stack', height=460,\n"
    "    xaxis=dict(title='PCAP',gridcolor=GRID),\n"
    "    yaxis=dict(title='% SOME/IP frames',gridcolor=GRID),\n"
    "    legend=dict(bgcolor=PANEL,bordercolor=GRID))\n"
    "show(fig)\n"
    "\n"
    "print(f'{\"PCAP\":<14}',end='')\n"
    "for mt in mt_order: print(f'{mt[:10]:>11}',end='')\n"
    "print()\n"
    "print('-'*104)\n"
    "for l in LABELS:\n"
    "    n_si=results[l]['n_si']\n"
    "    print(f'{l:<14}',end='')\n"
    "    for mt in mt_order:\n"
    "        cnt=results[l]['mt_counts'].get(mt,0)\n"
    "        pct=cnt/n_si*100 if n_si>0 else 0\n"
    "        print(f'{pct:>10.1f}%',end='')\n"
    "    print()"))

# ── SECTION 4: SERVICE IDs HEATMAP ────────────────────────────────────────────
cells.append(md("cell-h4", "## 4. Service IDs — Heatmap de Alvos por Ataque"))

cells.append(code("cell-svcid",
    "all_svcs=sorted(set(s for l in LABELS for s in results[l]['svc_counts']))\n"
    "\n"
    "z=[]\n"
    "for l in LABELS:\n"
    "    n_si=results[l]['n_si']\n"
    "    row=[results[l]['svc_counts'].get(s,0)/n_si*100 if n_si>0 else 0\n"
    "         for s in all_svcs]\n"
    "    z.append(row)\n"
    "\n"
    "text_z=[[f'{v:.0f}%' if v>0.5 else '' for v in row] for row in z]\n"
    "\n"
    "fig=go.Figure(go.Heatmap(\n"
    "    z=z, x=all_svcs, y=LABELS,\n"
    "    colorscale=[[0,'#0f1117'],[0.01,A],[0.3,Y],[1.0,R]],\n"
    "    hovertemplate='PCAP: %{y}<br>Service: %{x}<br>%{z:.1f}%<extra></extra>',\n"
    "    text=text_z, texttemplate='%{text}',\n"
    "    showscale=True))\n"
    "fig.update_layout(**LB,\n"
    "    title='Service ID — % dos frames SOME/IP (top 10 por PCAP)',\n"
    "    height=380,\n"
    "    xaxis=dict(title='Service ID',gridcolor=GRID,tickangle=30),\n"
    "    yaxis=dict(title='PCAP',gridcolor=GRID))\n"
    "show(fig)"))

# ── SECTION 5: VOLUME ────────────────────────────────────────────────────────
cells.append(md("cell-h5", "## 5. Volume e Taxa de Tráfego"))

cells.append(code("cell-volume",
    "fig=make_subplots(rows=1,cols=2,\n"
    "    subplot_titles=['Total de Frames','Taxa Média (pkt/s)'])\n"
    "\n"
    "frames_v=[results[l]['n_frame'] for l in LABELS]\n"
    "pps_v   =[results[l]['avg_pps']  for l in LABELS]\n"
    "\n"
    "fig.add_trace(go.Bar(\n"
    "    x=LABELS, y=frames_v, marker_color=COLORS,\n"
    "    text=[f'{v:,.0f}' for v in frames_v], textposition='outside',\n"
    "    hovertemplate='%{x}: %{y:,}<extra></extra>'),row=1,col=1)\n"
    "\n"
    "fig.add_trace(go.Bar(\n"
    "    x=LABELS, y=pps_v, marker_color=COLORS,\n"
    "    text=[f'{v:,.0f}' for v in pps_v], textposition='outside',\n"
    "    hovertemplate='%{x}: %{y:,.0f} pkt/s<extra></extra>'),row=1,col=2)\n"
    "\n"
    "fig.update_layout(**LB,title='Volume e taxa de tráfego',height=440,showlegend=False,\n"
    "    xaxis =dict(gridcolor=GRID,tickangle=30),\n"
    "    xaxis2=dict(gridcolor=GRID,tickangle=30),\n"
    "    yaxis =dict(title='Frames',gridcolor=GRID),\n"
    "    yaxis2=dict(title='pkt/s',gridcolor=GRID))\n"
    "show(fig)"))

# ── SECTION 6: TIME SERIES ────────────────────────────────────────────────────
cells.append(md("cell-h6", "## 6. Série Temporal — Intensidade SOME/IP (pkt/s)"))

cells.append(code("cell-ts",
    "attacks=[l for l in LABELS if l!='benign']\n"
    "\n"
    "fig=make_subplots(rows=2,cols=1,\n"
    "    subplot_titles=['Ataques — SOME/IP pkt/s','Benigno — SOME/IP pkt/s'],\n"
    "    vertical_spacing=0.12)\n"
    "\n"
    "for label,col in zip(attacks,COLORS[1:]):\n"
    "    ts=results[label]['ts']\n"
    "    t_vals=[x[0] for x in ts]\n"
    "    c_vals=[x[1] for x in ts]\n"
    "    fig.add_trace(go.Scatter(\n"
    "        x=t_vals, y=c_vals, name=label, mode='lines',\n"
    "        line=dict(color=col,width=1),\n"
    "        hovertemplate=f'{label}: %{{y}} pkt/s @ t=%{{x}}s<extra></extra>'),\n"
    "    row=1,col=1)\n"
    "\n"
    "if 'benign' in results:\n"
    "    ts_b=results['benign']['ts']\n"
    "    fig.add_trace(go.Scatter(\n"
    "        x=[x[0] for x in ts_b], y=[x[1] for x in ts_b],\n"
    "        name='benign', mode='lines',\n"
    "        line=dict(color=G,width=1),\n"
    "        hovertemplate='benign: %{y} pkt/s @ t=%{x}s<extra></extra>'),\n"
    "    row=2,col=1)\n"
    "\n"
    "fig.update_layout(**LB,title='Intensidade SOME/IP pkt/s',height=640,\n"
    "    xaxis =dict(title='t (s)',gridcolor=GRID),\n"
    "    xaxis2=dict(title='t (s)',gridcolor=GRID),\n"
    "    yaxis =dict(title='pkt/s',gridcolor=GRID),\n"
    "    yaxis2=dict(title='pkt/s',gridcolor=GRID),\n"
    "    legend=dict(bgcolor=PANEL,bordercolor=GRID))\n"
    "show(fig)\n"
    "\n"
    "print('Pico por PCAP:')\n"
    "for l in LABELS:\n"
    "    print(f'  {l:<14} {results[l][\"peak_pps\"]:>8,} pkt/s')"))

# ── SECTION 7: TTL ────────────────────────────────────────────────────────────
cells.append(md("cell-h7", "## 7. TTL — Anomalias por PCAP"))

cells.append(code("cell-ttl",
    "print(f'{\"PCAP\":<16} {\"TTLs observados\"}')\n"
    "print('-'*55)\n"
    "for l in LABELS:\n"
    "    ttls=results[l]['ttl']\n"
    "    flag='  << TTL=1 (possivel spoof)' if 1 in ttls else ''\n"
    "    print(f'{l:<16} {ttls}{flag}')"))

# ── SECTION 8: ATTACK CHARACTERISTICS ───────────────────────────────────────
cells.append(md("cell-h8", "## 8. Características de Ataque Detectáveis\n\n"
    "Indicadores derivados diretamente dos dados — comparação com baseline benigno."))

cells.append(code("cell-attack-char",
    "# ── Baseline benigno ────────────────────────────────────────────────────\n"
    "B = results['benign']\n"
    "b_sd_ratio   = B['n_sd'] / B['n_si'] * 100        # SD% normal\n"
    "b_0x1001     = B['svc_counts'].get('0x1001', 0)   # vol normal do svc principal\n"
    "b_n_ips      = B['n_ips']\n"
    "b_svcs       = set(B['svc_counts'].keys())\n"
    "attacks      = [l for l in LABELS if l != 'benign']\n"
    "\n"
    "# ── Calcular indicadores por ataque ──────────────────────────────────────\n"
    "rows = []\n"
    "for l in attacks:\n"
    "    r = results[l]\n"
    "    sd_ratio   = r['n_sd'] / r['n_si'] * 100 if r['n_si'] > 0 else 0\n"
    "    v_0x1001   = r['svc_counts'].get('0x1001', 0)\n"
    "    drop_0x1001= (1 - v_0x1001 / b_0x1001) * 100 if b_0x1001 > 0 else 0\n"
    "    new_svcs   = set(r['svc_counts'].keys()) - b_svcs\n"
    "    extra_ips  = r['n_ips'] - b_n_ips\n"
    "    rows.append(dict(label=l, sd_ratio=sd_ratio, drop_0x1001=drop_0x1001,\n"
    "                     new_svcs=new_svcs, extra_ips=extra_ips))\n"
    "\n"
    "# ── Heatmap de severidade dos indicadores ────────────────────────────────\n"
    "# Cada indicador normalizado 0-1 (0=normal, 1=máximo desvio observado)\n"
    "ind_labels = ['SD flood\\n(ratio SD%)', 'Disrupção\\n0x1001', 'Serviços\\ndesconhecidos', 'IPs extras']\n"
    "\n"
    "max_sd  = max(r['sd_ratio']  for r in rows)\n"
    "max_drop= max(r['drop_0x1001'] for r in rows)\n"
    "max_svcs= max(len(r['new_svcs']) for r in rows) or 1\n"
    "max_ips = max(r['extra_ips']  for r in rows) or 1\n"
    "\n"
    "z, text_z = [], []\n"
    "for r in rows:\n"
    "    row_z = [\n"
    "        r['sd_ratio']    / max_sd   if max_sd   > 0 else 0,\n"
    "        r['drop_0x1001'] / max_drop if max_drop > 0 else 0,\n"
    "        len(r['new_svcs']) / max_svcs,\n"
    "        max(r['extra_ips'], 0) / max_ips,\n"
    "    ]\n"
    "    row_t = [\n"
    "        f\"{r['sd_ratio']:.1f}%\",\n"
    "        f\"-{r['drop_0x1001']:.0f}%\",\n"
    "        ', '.join(sorted(r['new_svcs'])) if r['new_svcs'] else '—',\n"
    "        f\"+{r['extra_ips']}\" if r['extra_ips'] > 0 else '0',\n"
    "    ]\n"
    "    z.append(row_z)\n"
    "    text_z.append(row_t)\n"
    "\n"
    "fig = go.Figure(go.Heatmap(\n"
    "    z=z,\n"
    "    x=ind_labels,\n"
    "    y=[r['label'] for r in rows],\n"
    "    colorscale=[[0,'#0f1117'],[0.2,A],[0.6,Y],[1.0,R]],\n"
    "    zmin=0, zmax=1,\n"
    "    text=text_z, texttemplate='%{text}',\n"
    "    hovertemplate='%{y} — %{x}<br>valor: %{text}<extra></extra>',\n"
    "    showscale=False))\n"
    "fig.update_layout(**LB,\n"
    "    title='Indicadores de ataque — severidade relativa ao baseline benigno',\n"
    "    height=340,\n"
    "    xaxis=dict(side='top', gridcolor=GRID),\n"
    "    yaxis=dict(gridcolor=GRID))\n"
    "show(fig)\n"
    "\n"
    "# ── Tabela textual detalhada ──────────────────────────────────────────────\n"
    "print(f'Baseline benigno:')\n"
    "print(f'  SD ratio     : {b_sd_ratio:.1f}%')\n"
    "print(f'  Vol 0x1001   : {b_0x1001:,} frames')\n"
    "print(f'  IPs          : {b_n_ips}')\n"
    "print(f'  Services     : {sorted(b_svcs)}')\n"
    "print()\n"
    "print(f'{\"PCAP\":<14} {\"SD%\":>8} {\"SD anomalia\":>12} {\"Drop 0x1001\":>12} {\"Svcs novos\":>14} {\"IPs extras\":>10}')\n"
    "print('-'*74)\n"
    "for r in rows:\n"
    "    sd_flag = '<<ALTO' if r['sd_ratio'] > b_sd_ratio * 3 else '     '\n"
    "    dp_flag = f'-{r[\"drop_0x1001\"]:.0f}%' if r['drop_0x1001'] > 50 else f'-{r[\"drop_0x1001\"]:.0f}%'\n"
    "    dp_mark = '<<DISRUP' if r['drop_0x1001'] > 50 else ''\n"
    "    print(f'{r[\"label\"]:<14} {r[\"sd_ratio\"]:>7.1f}% {sd_flag:>12} {dp_flag:>10} {dp_mark:>14} {r[\"extra_ips\"]:>10}')\n"
    "    if r['new_svcs']:\n"
    "        print(f'  Serv. desconhecidos: {sorted(r[\"new_svcs\"])}')\n"
    "\n"
    "# ── Resumo das características observáveis ────────────────────────────────\n"
    "print()\n"
    "print('=' * 68)\n"
    "print('RESUMO — Características de Ataque Detectáveis')\n"
    "print('=' * 68)\n"
    "print()\n"
    "print('1. SD FLOOD (SOME/IP-SD ratio > 3x baseline)')\n"
    "print(f'   Baseline: {b_sd_ratio:.1f}%  |  Limiar: {b_sd_ratio*3:.1f}%')\n"
    "for r in rows:\n"
    "    mark = '  *** DETECTADO' if r['sd_ratio'] > b_sd_ratio * 3 else ''\n"
    "    print(f'   {r[\"label\"]:<14} {r[\"sd_ratio\"]:>6.1f}%{mark}')\n"
    "print()\n"
    "print('2. DISRUPÇÃO DE SERVIÇO (queda > 50% no volume do 0x1001)')\n"
    "print(f'   Baseline 0x1001: {b_0x1001:,} frames')\n"
    "for r in rows:\n"
    "    mark = '  *** DETECTADO' if r['drop_0x1001'] > 50 else ''\n"
    "    print(f'   {r[\"label\"]:<14} -{r[\"drop_0x1001\"]:>5.1f}% de queda{mark}')\n"
    "print()\n"
    "print('3. SERVIÇO DESCONHECIDO (service ID ausente no benigno)')\n"
    "for r in rows:\n"
    "    if r['new_svcs']:\n"
    "        print(f'   {r[\"label\"]:<14} {sorted(r[\"new_svcs\"])}  *** DETECTADO')\n"
    "    else:\n"
    "        print(f'   {r[\"label\"]:<14} nenhum')\n"
    "print()\n"
    "print('4. IP EXTRA (novos participantes vs baseline)')\n"
    "for r in rows:\n"
    "    mark = '  *** DETECTADO' if r['extra_ips'] > 0 else ''\n"
    "    print(f'   {r[\"label\"]:<14} +{r[\"extra_ips\"]} IP(s){mark}')"))

# ── SECTION 9: CHARACTERIZATION SUMMARY ─────────────────────────────────────
cells.append(md("cell-h9", "## 9. O que foi possível caracterizar"))

cells.append(code("cell-summary-char",
    "# ── Matriz de detecção ──────────────────────────────────────────────────\n"
    "# Status por ataque e por indicador\n"
    "# SIM=2 (verde), PARCIAL=1 (amarelo), NAO=0 (vermelho)\n"
    "B = results['benign']\n"
    "b_sd  = B['n_sd'] / B['n_si'] * 100\n"
    "b_001 = B['svc_counts'].get('0x1001', 0)\n"
    "b_ips = B['n_ips']\n"
    "b_svcs= set(B['svc_counts'].keys())\n"
    "attacks=[l for l in LABELS if l!='benign']\n"
    "\n"
    "SIM='SIM'; PARC='PARCIAL'; NAO='NÃO'\n"
    "GREEN='#1a3d1a'; YELLOW='#3d3300'; RED='#3d0f0f'\n"
    "TGREEN='#7bff9c'; TYELLOW='#ffd97b'; TRED='#ff7b7b'\n"
    "\n"
    "matrix = []\n"
    "for l in attacks:\n"
    "    r = results[l]\n"
    "    sd_ratio  = r['n_sd']/r['n_si']*100 if r['n_si']>0 else 0\n"
    "    drop_001  = (1 - r['svc_counts'].get('0x1001',0)/b_001)*100 if b_001>0 else 0\n"
    "    new_svcs  = set(r['svc_counts'].keys()) - b_svcs\n"
    "    extra_ips = r['n_ips'] - b_ips\n"
    "\n"
    "    sd_det  = SIM  if sd_ratio > b_sd*3   else (PARC if sd_ratio > b_sd*1.5 else NAO)\n"
    "    dp_det  = SIM  if drop_001 > 50        else (PARC if drop_001 > 20        else NAO)\n"
    "    sv_det  = SIM  if new_svcs             else NAO\n"
    "    ip_det  = SIM  if extra_ips > 0        else NAO\n"
    "    # detectavel por metadados = pelo menos 1 SIM\n"
    "    overall = SIM  if SIM in [sd_det,dp_det,sv_det,ip_det] \\\n"
    "              else (PARC if PARC in [sd_det,dp_det,sv_det,ip_det] else NAO)\n"
    "    matrix.append([l, sd_det, dp_det, sv_det, ip_det, overall])\n"
    "\n"
    "cols_h = ['Ataque','SD Flood','Disrupção\\nde Serviço',\n"
    "          'Serviço\\nInjetado','IP Extra','Detectável por\\nMetadados']\n"
    "\n"
    "def cell_color(v):\n"
    "    return GREEN if v==SIM else (YELLOW if v==PARC else RED)\n"
    "def text_color(v):\n"
    "    return TGREEN if v==SIM else (TYELLOW if v==PARC else TRED)\n"
    "\n"
    "fill_cols = [[BG]*len(matrix)]  # coluna label sempre escura\n"
    "font_cols = [[TEXT]*len(matrix)]\n"
    "for ci in range(1, len(cols_h)):\n"
    "    fill_cols.append([cell_color(row[ci]) for row in matrix])\n"
    "    font_cols.append([text_color(row[ci]) for row in matrix])\n"
    "\n"
    "fig = go.Figure(go.Table(\n"
    "    header=dict(values=cols_h,\n"
    "                fill_color=PANEL,\n"
    "                font=dict(color=A, size=12),\n"
    "                align='center', height=40),\n"
    "    cells=dict(\n"
    "        values=[[row[i] for row in matrix] for i in range(len(cols_h))],\n"
    "        fill_color=fill_cols,\n"
    "        font=dict(color=font_cols, size=12, family='monospace'),\n"
    "        align='center', height=36)))\n"
    "fig.update_layout(**LB,\n"
    "    title='Matriz de detecção — o que é visível nos metadados de rede',\n"
    "    height=320)\n"
    "show(fig)\n"
    "\n"
    "# ── Modelo de ameaça ─────────────────────────────────────────────────────\n"
    "threat_html = '''\n"
    "<div style=\"background:#161b2e;border-left:4px solid #4e7fff;\n"
    "            padding:18px 24px;margin:18px 0;font-family:monospace;\n"
    "            color:#d0d8f0;border-radius:4px;\">\n"
    "<h3 style=\"color:#4e7fff;margin-top:0\">Modelo de Ameaça — o que os dados implicam</h3>\n"
    "<p><b style=\"color:#7bff9c\">Vetor de acesso:</b> atacante já está <i>dentro</i> da rede\n"
    "   (IPs no mesmo segmento 172.18.0.x). Não é intrusão externa.</p>\n"
    "<p><b style=\"color:#7bff9c\">Ausência de autenticação:</b> qualquer nó pode anunciar\n"
    "   qualquer Service ID. O 0x100b do mitm_multi aparece sem resistência na rede.</p>\n"
    "<p><b style=\"color:#7bff9c\">SD como ponto fraco:</b> SOME/IP-SD não valida quem pode\n"
    "   fazer Offer de um serviço. Três ataques (dos_noti, mitm_single, mitm_multi)\n"
    "   exploram isso — SD ratio dispara até 42.7% vs 1.7% no benigno.</p>\n"
    "<p><b style=\"color:#7bff9c\">DoS por substituição, não por volume:</b> dos_noti mantém\n"
    "   a mesma taxa de pacotes (~1300 pkt/s). O ataque desloca tráfego legítimo,\n"
    "   não satura a banda.</p>\n"
    "<p><b style=\"color:#ffd97b\">Fuzzy(1) e fuzzy(3) são invisíveis por metadados:</b>\n"
    "   estatísticas globais idênticas ao benigno. O ataque está no conteúdo dos\n"
    "   campos SOME/IP — requer inspeção de payload para ser detectado.</p>\n"
    "</div>\n"
    "'''\n"
    "display(HTML(threat_html))\n"
    "\n"
    "# ── O que não foi possível determinar ────────────────────────────────────\n"
    "limits_html = '''\n"
    "<div style=\"background:#1a1200;border-left:4px solid #ffd97b;\n"
    "            padding:18px 24px;margin:18px 0;font-family:monospace;\n"
    "            color:#d0d8f0;border-radius:4px;\">\n"
    "<h3 style=\"color:#ffd97b;margin-top:0\">Limitações — o que requer inspeção de payload</h3>\n"
    "<ul style=\"margin:0;padding-left:20px\">\n"
    "<li><b>Fuzzy(1) e fuzzy(3):</b> indistinguíveis do benigno por distribuição de pacotes.\n"
    "    O ataque está nos valores dos campos SOME/IP (Method ID, Return Code, payload bytes).</li>\n"
    "<li><b>Timestamp de início do ataque:</b> não há ground truth de quando cada ataque começa\n"
    "    dentro do PCAP — a janela de ataque é desconhecida.</li>\n"
    "<li><b>Intenção vs ruído:</b> a queda de 0x1001 pode ser consequência do ataque ou\n"
    "    comportamento normal do sistema naquele momento.</li>\n"
    "</ul>\n"
    "</div>\n"
    "'''\n"
    "display(HTML(limits_html))"))

# ── ASSEMBLE ──────────────────────────────────────────────────────────────────
nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name":"Python 3","language":"python","name":"python3"},
        "language_info": {"name":"python","version":"3.13.0"}
    },
    "nbformat": 4,
    "nbformat_minor": 5
}

with open(OUT, 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print(f'Criado: {OUT}')
